### ISSUE TITLE
Datastore costs?

### ISSUE THREAD

**Issue by ajck** [tomwalder/php-gds-session#2]
This is excellent, thanks very much for releasing.

Just wondering is there any way of getting an idea of Datastore financial costs for using this, e.g. per user on a site - i.e. storage costs and Datastore operations costs? How would one calculate this (even roughly)?

Thanks again.

**Comment by tomwalder** [comment]
You're welcome!

Costs should be reasonable - although I've not done the maths yet!

The system comes with a memcache layer for reading when possible, so Datastore reads are minimised.

**Comment by tomwalder** [comment]
As an FYI, here are the basic costs

https://cloud.google.com/datastore/docs/pricing

**Comment by iamacarpet** [comment]
@ajck we've been using our own, maybe not so well written version of this as part of Laravel over at [a1comms/GaeSupportL5](https://github.com/a1comms/GaeSupportL5) for a few months now on a site with about 1,000,000 monthly page views, of those about 300,000 being unique visitors generating new sessions.
We use Datastore for more than just sessions, so it's not a great comparison, but even so we'd be lucky to spend 5 GBP outside of the free tier per month on Datastore, with a small amount of dedicated memcache to aid caching at about 30 GBP per month.
Overall, I'd say it's a great storage layer for performance and pricing, the only downside being it's not so easy for the developers to work with, but arguably worth the trade-off.

**Comment by tomwalder** [comment]
Thanks for the input, @iamacarpet - much appreciated!

**Comment by ajck** [comment]
Yes, thanks very much @iamacarpet and @tomwalder
