### ISSUE TITLE
REST API v1 changes?

### ISSUE THREAD

**Issue by eurobob** [tomwalder/php-gds-session#5]
I'm getting this error when using the library on GCE:

`Fatal error: Uncaught exception 'Exception' with message 'Could not determine DATASET, please pass to GDS\Gateway\ProtoBuf::__construct()' in /var/www/writerhythm.com/htdocs/vendor/tomwalder/php-gds/src/GDS/Gateway/ProtoBuf.php:70 Stack trace: #0 /var/www/writerhythm.com/htdocs/vendor/tomwalder/php-gds-session/src/GDS/Session/Handler.php(271): GDS\Gateway\ProtoBuf->__construct() #1 /var/www/writerhythm.com/htdocs/vendor/tomwalder/php-gds-session/src/GDS/Session/Handler.php(176): GDS\Session\Handler->getStore() #2 [internal function]: GDS\Session\Handler->read('s965i6516js16kf...') #3 /var/www/writerhythm.com/htdocs/vendor/tomwalder/php-gds-session/src/GDS/Session/Handler.php(105): session_start() #4 /var/www/writerhythm.com/htdocs/wp-content/plugins/cfx_campaign/inc/class.CFX_Campaign_Manager.php(48): GDS\Session\Handler::start() #5 /var/www/writerhythm.com/htdocs/wp-content/plugins/cfx_campaign/inc/class.CFX_Campaign_Manager.php(26): CFX_Campaign_Manager->__construct() #6 /var/www/writerhythm.com/htdocs/wp-content/plugin in /var/www/writerhythm.com/htdocs/vendor/tomwalder/php-gds/src/GDS/Gateway/ProtoBuf.php on line 70`

Does it need updating to work with the REST API? Some documentation would be much appreciated :)

**Comment by tomwalder** [comment]
The library now uses PHP-GDS 3.x, so theoretically could work with the REST API - however, it is designed for use on AppEngine standard runtime, so directly uses the faster ProtocolBuffer API.
